name: Package vscode-json-languageserver

on:
  workflow_dispatch:
    inputs:
      vscode-json-languageserver_version:
        type: string
        required: true
      patches_version:
        type: string
        required: true

jobs:
  package_all:
    name: Package JSON Language Server
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      VERSION: ${{ inputs.vscode-json-languageserver_version }}
      PATCHES_VERSION: ${{ inputs.patches_version }}
      PATCHED_VERSION: ${{ inputs.vscode-json-languageserver_version }}-patch-${{ inputs.patches_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Update Packages
        run: sudo apt-get update -y
      - name: Install Dependencies
        run: sudo apt-get install -y npm nodejs
      - name: Get vscode
        run: |
          curl -L -o "v${VERSION}.tar.gz" "https://github.com/microsoft/vscode/archive/refs/tags/${VERSION}.tar.gz"
      - name: Build vscode-json-languageserver
        run: |
          tar -xzvf "v${VERSION}.tar.gz"
          git apply --directory=vscode-${VERSION} patches/vscode-json-languageserver/*.patch --verbose
          cd "vscode-${VERSION}/extensions/json-language-features/server"
          npm i @vercel/ncc typescript
          # replace /umd/ with /esm/ in some require paths,
          # as /umd/ files don't seem to get picked up by ncc
          sed -i 's/\/umd\//\/esm\//g' node_modules/vscode-json-languageservice/package.json
          npx ncc build src/node/jsonServerNodeMain.ts --license LICENSES
      - name: Package
        run: |
          mkdir bundle
          cp -r vscode-${VERSION}/LICENSE.txt vscode-${VERSION}/extensions/json-language-features/server/dist bundle
          mv bundle vscode-json-languageserver
          tar -zcvf vscode-json-languageserver-${PATCHED_VERSION}.tar.gz vscode-json-languageserver
      - name: Create Release
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        run: |
          gh release delete -y "vscode-json-languageserver-${PATCHED_VERSION}" || true
          gh release create -t "vscode-json-languageserver-${PATCHED_VERSION}" "vscode-json-languageserver-${PATCHED_VERSION}" "vscode-json-languageserver-${PATCHED_VERSION}.tar.gz"
